#yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json

package: swapi
generate:
  std-http-server: true
  embedded-spec: true
  models: true
output: ./generated/api.gen.go